#%RAML 1.0 DataType
type: object
additionalProperties: false
properties:
  addressId:
    type: string
    required: true
    example: A000001
  postalCode:
    type: string
    required: true
    example: 100-0001
  prefecture:
    type: string
    required: true
    example: 東京都
  city:
    type: string
    required: true
    example: 千代田区
  addressLine1:
    type: string
    required: true
    example: 1-1-1
  addressLine2?:
    type: string
    example: サンプルビル
