#%RAML 1.0 Trait
responses:
  400:
    description: リクエストが不正です。
    body:
      application/json:
        type: ErrorResponse
        example: !include ../examples/error-response.json
  404:
    description: 指定されたリソースが見つかりません。
    body:
      application/json:
        type: ErrorResponse
        example: !include ../examples/error-response.json
  500:
    description: 内部サーバーエラーです。
    body:
      application/json:
        type: ErrorResponse
        example: !include ../examples/error-response.json
  503:
    description: 接続先サービスが利用できません。
    body:
      application/json:
        type: ErrorResponse
        example: !include ../examples/error-response.json
  504:
    description: 接続先サービスがタイムアウトしました。
    body:
      application/json:
        type: ErrorResponse
        example: !include ../examples/error-response.json
