#%RAML 1.0
title: サンプル住所API
version: v1
baseUri: https://api.example.com/api/v1
mediaType: application/json

annotationTypes:
  operationId:
    type: string

types:
  Address: !include types/Address.raml
  AddressList: !include types/AddressList.raml
  ErrorResponse: !include ../../common/types/ErrorResponse.raml

traits:
  correlation-id: !include ../../common/traits/correlation-id.raml
  common-errors: !include ../../common/traits/common-errors.raml

/customers:
  /{customerId}:
    uriParameters:
      customerId:
        type: string
        required: true
        example: C000001
    /addresses:
      get: !include resources/address-get-by-customer-id.raml
